# Generated by Django 5.0.6 on 2024-11-20 22:31

import mainApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBUS_Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_id', models.CharField(default=mainApp.models.modalID_generator, editable=False, max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='candidates')),
                ('bio', models.TextField(null=True)),
                ('position', models.TextField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Event Coordinator', 'Event Coordinator'), ('Sports and Recreation Officer', 'Sports and Recreation Officer'), ('Cultural affairs officer', 'Cultural affairs officer'), ('Department Representative', 'Department Representative')], null=True)),
            ],
            options={
                'verbose_name': 'CBUS Candidate',
                'verbose_name_plural': 'CBUS Candidates',
            },
        ),
        migrations.CreateModel(
            name='CECS_Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_id', models.CharField(default=mainApp.models.modalID_generator, editable=False, max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='candidates')),
                ('bio', models.TextField(null=True)),
                ('position', models.TextField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Event Coordinator', 'Event Coordinator'), ('Sports and Recreation Officer', 'Sports and Recreation Officer'), ('Cultural affairs officer', 'Cultural affairs officer'), ('Department Representative', 'Department Representative')], null=True)),
            ],
            options={
                'verbose_name': 'CECS Candidate',
                'verbose_name_plural': 'CECS Candidates',
            },
        ),
        migrations.CreateModel(
            name='CLA_Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_id', models.CharField(default=mainApp.models.modalID_generator, editable=False, max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='candidates')),
                ('bio', models.TextField(null=True)),
                ('position', models.TextField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Event Coordinator', 'Event Coordinator'), ('Sports and Recreation Officer', 'Sports and Recreation Officer'), ('Cultural affairs officer', 'Cultural affairs officer'), ('Department Representative', 'Department Representative')], null=True)),
            ],
            options={
                'verbose_name': 'CLA Candidate',
                'verbose_name_plural': 'CLA Candidates',
            },
        ),
        migrations.CreateModel(
            name='CSM_Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_id', models.CharField(default=mainApp.models.modalID_generator, editable=False, max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='candidates')),
                ('bio', models.TextField(null=True)),
                ('position', models.TextField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Event Coordinator', 'Event Coordinator'), ('Sports and Recreation Officer', 'Sports and Recreation Officer'), ('Cultural affairs officer', 'Cultural affairs officer'), ('Department Representative', 'Department Representative')], null=True)),
            ],
            options={
                'verbose_name': 'CSM Candidate',
                'verbose_name_plural': 'CSM Candidates',
            },
        ),
        migrations.CreateModel(
            name='MAIN_Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_id', models.CharField(default=mainApp.models.modalID_generator, editable=False, max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='candidates')),
                ('bio', models.TextField(null=True)),
                ('position', models.TextField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Event Coordinator', 'Event Coordinator'), ('Sports and Recreation Officer', 'Sports and Recreation Officer'), ('Cultural affairs officer', 'Cultural affairs officer'), ('Department Representative', 'Department Representative')], null=True)),
            ],
            options={
                'verbose_name': 'MAIN-WSU Candidate',
                'verbose_name_plural': 'MAIN-WSU Candidates',
            },
        ),
        migrations.CreateModel(
            name='UserRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('president', models.CharField(blank=True, max_length=50, null=True)),
                ('vice_president', models.CharField(blank=True, max_length=50, null=True)),
                ('treasurer', models.CharField(blank=True, max_length=50, null=True)),
                ('secretary', models.CharField(blank=True, max_length=50, null=True)),
                ('event_coordinator', models.CharField(blank=True, max_length=50, null=True)),
                ('sports_recreation_officer', models.CharField(blank=True, max_length=50, null=True)),
                ('cultural_affairs_officer', models.CharField(blank=True, max_length=50, null=True)),
                ('departmentrepresentative', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'RECORDS',
                'verbose_name_plural': 'RECORDS',
            },
        ),
        migrations.CreateModel(
            name='votingschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField(choices=[('CECS', 'CECS'), ('CSM', 'CSM'), ('CLA', 'CLA'), ('CBUS', 'CBUS')], null=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'verbose_name': 'Voting Schedules',
                'verbose_name_plural': 'Voting Schedules',
            },
        ),
    ]
